name: Build and Deploy Hugo site to /docs folder on main branch

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dart Sass
        run: npm install -g sass

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.119.0'
          extended: true

      - name: Build site
        run: hugo --minify

      - name: Copy public to docs
        run: |
          rm -rf docs
          mkdir docs
          cp -r public/* docs/

      - name: Commit and Push changes to main branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs
          git commit -m "Actualizar sitio en /docs [skip ci]" || echo "No hay cambios para commitear"
          git push origin main
